export const Limits = {
    MIN_USERNAME_LENGTH: 5,
    MAX_USERNAME_LENGTH: 15,
    MIN_PASSWORD_LENGTH: 5,
    MAX_PASSWORD_LENGTH: 15,
    MAX_BOOK_TITLE_LENGTH: 20,
    MIN_BOOK_TITLE_LENGTH: 3,
    MAX_BOOK_CONTENT_LENGTH: 50,
    MIN_BOOK_CONTENT_LENGTH: 3,
    MIN_REVIEW_LENGTH: 3,
    MAX_REVIEW_LENGTH: 20,
}